### ISSUE TITLE
Highlight problem of vimshellCommand

### ISSUE THREAD

**Issue by itchyny** [Shougo/vimshell.vim#183]
Only the first command is highlighted by `vimshellCommand`.

![screen shot 2015-01-21 at 2 37 27 pm](https://cloud.githubusercontent.com/assets/375258/5831712/29d79930-a17b-11e4-9454-8b1cc6cf80dc.png)

Test case
```vim
sleep 0; sleep 0 || sleep 0 && sleep 0; sleep 0
```

**Comment by Shougo** [comment]
Fixed.

**Comment by itchyny** [comment]
Thanks!
