### ISSUE TITLE
can't use the command  :VimShell

### ISSUE THREAD

**Issue by foxundermoon** [Shougo/vimshell.vim#184]
[vimshell] Detected autochdir!
[vimshell] vimshell don't work if you set autochdir option.

when i press the Enter,this is error message!

**Comment by foxundermoon** [comment]
vim version  7.4.558
VimShell  the last version,
i don't know where wrong~~~~

**Comment by ujihisa** [comment]
vimshell doesn't work if you set autochdir option.
