### ISSUE TITLE
VimShellSendString to ipython and not regular python

### ISSUE THREAD

**Issue by petobens** [Shougo/vimshell.vim#185]
How do I force `:VimShellSendString` to use `ipython` instead of `python`?

![foo](https://cloud.githubusercontent.com/assets/2583971/5982758/3bfa1a9e-a8a5-11e4-908f-8f238acd340a.gif)

**Comment by Shougo** [comment]
`:help g:vimshell_interactive_interpreter_commands`

**Comment by petobens** [comment]
@Shougo  I've read the documentation but I still don't understand how to associate python files with `ipython` interpreter. Please tell me how to do it from my vimrc. Thank you

**Comment by Shougo** [comment]
```vim
if !exists('g:vimshell_interactive_interpreter_commands')
  let g:vimshell_interactive_interpreter_commands = {}
endif
let g:vimshell_interactive_interpreter_commands.python = 'ipython'
```

**Comment by petobens** [comment]
With the following minimal  vimrc it doesn't work:

    set nocompatible

    let $ONEDRIVE_HOME = expand('C:/OD/Users/Pedro/')
    let $DOTVIM = expand('$ONEDRIVE_HOME/vimfiles')

    set runtimepath+=$DOTVIM/bundle/vimproc
    set runtimepath+=$DOTVIM/bundle/vimshell/
    filetype plugin indent on

    if !exists('g:vimshell_interactive_interpreter_commands')
        let g:vimshell_interactive_interpreter_commands = {}
    endif
    let g:vimshell_interactive_interpreter_commands.python = 'ipython3'

    vnoremap <silent> ,ei :VimShellSendString<CR>

![blah](https://cloud.githubusercontent.com/assets/2583971/6029091/f855e81a-abcc-11e4-835e-fbf752a34581.gif)

**Comment by Shougo** [comment]
Fixed.

**Comment by petobens** [comment]
Great. Thank you!
