### ISSUE TITLE
Evaluate visual selection in VimShell popup

### ISSUE THREAD

**Issue by petobens** [Shougo/vimshell.vim#187]
Consider the following minimal vimrc

    set nocompatible

    let $ONEDRIVE_HOME = expand('C:/OD/Users/Pedro/')
    let $DOTVIM = expand('$ONEDRIVE_HOME/vimfiles')

    set runtimepath+=$DOTVIM/bundle/vimproc
    set runtimepath+=$DOTVIM/bundle/vimshell/

    filetype plugin indent on
    set guioptions=ac
    set splitbelow

    function! EvaluatePython()
        VimShellBufferDir -popup
        let command = @*
        let command = "'" . command . "'"
        execute 'VimShellSendString python -c ' . command
        wincmd p
    endfunction

    vnoremap <silent> ,ep :call EvaluatePython()<CR>

and (as it is done in the Gif) open a file `foo.py` with the following content

    print("hello world")
    print('foo')

Now visually select the first line and press `,ep`, you will see that the visual selection is correctly evaluated. Now visually select the second line and once again run `,ep`, you will now see that the python interpreter shows errors. 

So my question is: how should I modifiy the `EvaluatePython()` so I can visually select some lines and evaluate them in a VimShell buffer (not in the interpreter)? There is clearly something wrong in my function with single and double quotes and shellescaping but I don't know how to fix it.

![blah](https://cloud.githubusercontent.com/assets/2583971/6046817/234d2c06-ac84-11e4-81ad-60edd2f4971c.gif)

**Comment by ujihisa** [comment]
`:h escape()`

**Comment by petobens** [comment]
@ujihisa  Can you show me how to use `escape()` to fix my particular function (example)?

**Comment by Shougo** [comment]
Yes.  You must escape arguments like this:

```vim
let command = "'" . substitute(command, "'", "''", 'g') . "'"
```

**Comment by petobens** [comment]
Great @Shougo thanks. Now however I've encountered another problem: if with the minimal vimrc (escaping arguments as you suggest) I now select the first line and type `,ep` and then select both the first and second lines and type `,ep` I get a prompt asking:

    The process is still running. Kill it? [yes/no]:

How can I avoid that message?

**Comment by petobens** [comment]
Great @Shougo thanks. Now however I've encountered another problem: if with the minimal vimrc (escaping arguments as you suggest) I now select the first line and type `,ep` and then select both the first and second lines and type `,ep` I get a prompt asking:

    The process is still running. Kill it? [yes/no]:

How can I avoid that message?

**Comment by Shougo** [comment]
Confirmed.  It is your command's bug.
You should define command like `:VimShellSendString` for it.

```vim
command! -range -nargs=? VimShellSendString
      \ call vimshell#interactive#send_region(<line1>, <line2>, <q-args>)
```

**Comment by Shougo** [comment]
Your function is called twice for the range.  So, vimshell prompts "Kill the previous process?"

**Comment by petobens** [comment]
> You should define command like :VimShellSendString for it.

@Shougo I don't understand how to modify my `EvaluatePython()` function the way you say. Can you please show me how to do it? Thank you

**Comment by petobens** [comment]
@Shougo I'm terrible sorry to bother you again but since you know way more vimscript than myself can you please tell me how to modify my function in order to evaluate a range without calling it twice? Thank you

**Comment by Shougo** [comment]
Unfortunatelly, I have not much time for it.   I'm busy for other plugins issues..

@ujihisa Can you provide the code?

**Comment by petobens** [comment]
@Shougo thanks anyway. I hope @ujihisa can help me.

**Comment by petobens** [comment]
>You should define command like :VimShellSendString for it.

@Shougo I finally figured out what you meant. Thank you for the advice and guidance.
