### ISSUE TITLE
VimShellTab should close tab after exit

### ISSUE THREAD

**Issue by p0deje** [Shougo/vimshell.vim#192]
Hello, and thanks for an amazing plugin!

I think the way VimShell behaves upon exit is a little weird when used with tab.

Steps to reproduce:

1. Open new Vim instance.
2. Execute `:VimShellTab`.
3. Send `exit` to vimshell.

Expected result: vimshell buffer is closed and tab is closed.
Actual result: vimshell buffer is closed and empty buffer is loaded.

**Comment by Shougo** [comment]
I don't think so.  But if other people wanted the feature, I will change the behavior.

**Comment by p0deje** [comment]
Why don't you think it should be closed? `:VimShellTab` opens new tab, so if exiting vimshell closes this tab, that makes perfect sense to me.

Maybe there is a different way to alter this behavior?

**Comment by Shougo** [comment]
User may open files in the tab.  User may want to switch other buffers.

**Comment by Shougo** [comment]
Fixed.
