### ISSUE TITLE
exe --eocodingで文字コード指定してコマンド実行後に内部コマンドの出力が文字化けする

### ISSUE THREAD

**Issue by shiena** [Shougo/vimshell.vim#195]
`exe --encoding`で`&encoding`と異なる文字コードを指定してコマンドを実行すると
内部コマンドやvimscriptの関数の出力が文字化けします。

動作環境
Windows8.1
Kaoriya-Vim@7.4.648
vimshell@9fef1b544352dd3d639ca992eab95b6c73f346ea

以下は`encoding=cp932`の環境で内部コマンドの`pwd`および`getcwd()`を
`exe --encoding=utf8 ls`の前後で実行したキャプチャです。
後に実行した方の出力が文字化けしています。

![vimshell](https://cloud.githubusercontent.com/assets/1295639/7417715/0332c4e6-efa3-11e4-813d-5ffa2519f024.png)

**Comment by Shougo** [comment]
encodingオプションが変わっていないのに内部コマンドが文字化けするのは正直妙な話です。
そのlsコマンドが怪しいので、他のコマンドでも再現するか試してもらえますか。

**Comment by shiena** [comment]
承知しました。
他のコマンドで再現しないか試してみます。

ちなみにlsコマンドはSourceTree経由でインストールしたPortable Git (version 1.9.5-preview20141217)に含まれているものです。

**Comment by shiena** [comment]
内部コマンドと外部コマンドでそれぞれ確認してみました。

| 文字化け確認用内部コマンド | encoding=utf8指定コマンド | 結果 |
|----------------------------|---------------------------|------|
| pwd                        | ls                        | NG   |
| echo                       | ls                        | NG   |
| history                    | ls                        | NG   |
| pwd                        | dir                       | NG   |
| echo                       | dir                       | NG   |
| history                    | dir                       | NG   |

| 文字化け確認用外部コマンド | encoding=utf8指定コマンド | 結果 |
|----------------------------|---------------------------|------|
| ping                       | ls                        | OK   |
| dir                        | ls                        | OK   |
| ping                       | dir                       | OK   |
| dir                        | dir                       | OK   |

* ls (Portable Git)
* ping (Windowsのコマンド)
* dir (cmdの内部コマンド)

文字化けが起きるのはvimshellの内部コマンドだけのようです。
また、以下のように内部コマンドが文字化けした後でも外部コマンドを実行すると文字化けが起きなくなりました。

1. pwd (文字化けなし)
1. exe --encoding=utf8 ls
1. pwd (文字化けあり)
1. dir (文字化けなし)
1. pwd (文字化けなし)

**Comment by Shougo** [comment]
修正しました

**Comment by shiena** [comment]
ありがとうございます。文字化けが起きなくなりました。
