### ISSUE TITLE
pressing <Q> closes more than just the vimshell buffer

### ISSUE THREAD

**Issue by jpnk** [Shougo/vimshell.vim#200]
open a new tab with

    :VimShellTab -create

then open a file with

    $ vim test

then switch back to the vimshell buffer and press __Q__. the entire tab gets closed instead of just the buffer.

**Comment by Shougo** [comment]
Yes, it is feature.
It closes current tab if you use "VimShellTab".

**Comment by jpnk** [comment]
can i switch it to normal behavior somehow?

**Comment by Shougo** [comment]
No.

**Comment by jpnk** [comment]
i'd like to request this then because the current behavior isn't always what you want. e.g. you open a new tab then open one or more files like above and then realize you don't need the shell buffer anymore. currently there's no way to close the buffer without closing the entire tab.

**Comment by Shougo** [comment]
You can use `tabopen | VimShell` instead.
