### ISSUE TITLE
support ~/.vim/vimshrc in addition to ~/.vimshrc

### ISSUE THREAD

**Issue by jpnk** [Shougo/vimshell.vim#201]
when looking for '.vimrc' vim check these two paths:

- $HOME/.vimrc
- $HOME/.vim/vimrc

the last one is very handy because you can keep all your vim-specific stuff inside $HOME/.vim. would be nice if vimshell also supported this.

**Comment by Shougo** [comment]
Implemented.

**Comment by jpnk** [comment]
thanks!
