### ISSUE TITLE
& in a string is not properly treated

### ISSUE THREAD

**Issue by itchyny** [Shougo/vimshell.vim#206]
`echo '&'` should not be interpreted as opening a background process, but just echoes a string `&`.

**Comment by itchyny** [comment]
Weird. `echo 'foo & bar'` works well but `echo 'foo &'` opens the bg-echo buffer. `'foo &'` should be parsed as a string, too.

**Comment by Shougo** [comment]
Reproduced.

**Comment by itchyny** [comment]
Thanks!
