### ISSUE TITLE
print python user input

### ISSUE THREAD

**Issue by petobens** [Shougo/vimshell.vim#208]
Consider the following python file:

```py
user_input = input('Enter some word: ')
print(user_input)
```

Open `Gvim`, and in the directory of that file run `:VimShell -popup`. Once the vimshell buffer opens run `python bar.py`. You will see, as in the GIF, that vimshell accepts the user input (`foo`) but when I press enter it returns (instead of printing `foo`). The expected behaviour is the one seen in the second GIF where I run the python file from the cmd prompt:

![blahh](https://cloud.githubusercontent.com/assets/2583971/9534759/6a5d0522-4cf1-11e5-94e5-b1339723a60e.gif)

![blah2](https://cloud.githubusercontent.com/assets/2583971/9534758/6a5c34e4-4cf1-11e5-8cdb-05da4de84675.gif)

**Comment by ujihisa** [comment]
This has 2 completely independent issues.

1. You are using python wrong. `input` is to accept user input and evaluate it. `foo` variable doesn't exist, so it fails
2. Your vimshell for some reason doesn't show any STDERR outputs. This seems to be a bug or misconfiguration

**Comment by Shougo** [comment]
Unfortunatelly, in Windows, user input featurer is not supported.
Windows does not have PTY.

**Comment by petobens** [comment]
Thanks @Shougo.
