### ISSUE TITLE
Vimshell makes navigation between splits with ctrl-w difficult

### ISSUE THREAD

**Issue by ignovak** [Shougo/vimshell.vim#209]
When I open vimshell in one of the several open splits, it becomes difficult to move between them using mappings starting with `ctrl-w`. If I exec `set showcmd`, I can see that when pressing `ctrl-w` the sign `^W` shows up in status line but then quickly disappears. So the only way to move between the splits is to press `<c-w>w` quickly enough, that is not very convenient.

Once the vimshell-buffer hides, `ctrl-w` functionality starts to work well again.

Video: https://yadi.sk/i/CWfAxA_4ipYk5.

**Comment by Shougo** [comment]
It is feature.
You can change `g:vimshell_interactive_update_time` value.

**Comment by ignovak** [comment]
Oh, ok. I thought that this variable relates Insert mode only and didn't try to change it in .vimrc.

Thank you.
