### ISSUE TITLE
<Plug>(vimshell_hide) closes the window

### ISSUE THREAD

**Issue by WscriChy** [Shougo/vimshell.vim#211]
Why <Plug>(vimshell_hide) closes the window if it was not opened in a split window (so no split or popup options)? Should not it to restore the previous buffer in the window?

**Comment by Shougo** [comment]
You can create Pull request for it.

**Comment by fcymk2** [comment]
@WscriChy  you can use vim-bbye to do this  by :Bdelete<CR>
