### ISSUE TITLE
Vimshell screen update

### ISSUE THREAD

**Issue by petobens** [Shougo/vimshell.vim#212]
Why is that when I run a command from the vimshell buffer then the output is inmediately updated but if I run it with `VimShellSendString` the vimshell buffer only updates when I move the cursor?

For instance in the first part of the GIF i'm running `pdflatex` on a `tex` file. You can see that the vimshell buffer is constantly updating the output. On the the other hand, in the second part of the GIF, I'm running the same command but with `VimShellSendString` and you can see that the output does not update (unless I move the cursor). Is there are a way to automatically update the vimshell buffer when using `VimShellSendString?`.

![blahh](https://cloud.githubusercontent.com/assets/2583971/11301836/985c80dc-8f78-11e5-9e44-e96187968f8e.gif)

**Comment by Shougo** [comment]
Fixed.

**Comment by petobens** [comment]
Thanks Shougo. However now when I try to exit the Vimshell buffer with the `Q` mapping I get:

```
Error detected while processing function vimshell#interactive#hang_up:
line    7:
E121: Undefined variable: b:interactive
E116: Invalid arguments for function s:is_valid(b:interactive)
E15: Invalid expression: !s:is_valid(b:interactive)
```

Another question: as you can see in the GIF now the buffer indeed gets updated but if I switch from normal mode to insert mode the updating stops, is this expected? 
Also: why do I get the flickering on the tabline? Is this because your solution in order to update basically constantly switches from one buffer to another one? If that's the case, can it be improved?

![gif](https://cloud.githubusercontent.com/assets/2583971/11315434/6a5030f0-8fd0-11e5-9e46-d5b4a051a9bd.gif)

**Comment by Shougo** [comment]
> Another question: as you can see in the GIF now the buffer indeed gets updated but if I switch from normal mode to insert mode the updating stops, is this expected? 

It is expected behavior.  The auto update is in Normal mode only.

**Comment by Shougo** [comment]
> Thanks Shougo. However now when I try to exit the Vimshell buffer with the Q mapping I get:

Fixed the error.  Please update vimshell.

> Also: why do I get the flickering on the tabline? Is this because your solution in order to update basically constantly switches from one buffer to another one? If that's the case, can it be improved?

It is Vim's feature.  The tabline is updated when auto update.  I cannot improve it.

**Comment by petobens** [comment]
> Fixed the error. Please update vimshell.
After updating I get the following error:

```
Error detected while processing function vimshell#interactive#hang_up[8]..<SNR>145_kill_process:
line    2:
E716: Key not present in Dictionary: waitpid()
E15: Invalid expression: a:interactive.process.waitpid()
line    3:
E121: Undefined variable: cond
E15: Invalid expression: cond != 'exit'
line   13:
E121: Undefined variable: cond
E15: Invalid expression: [cond, status]
```

> It is Vim's feature. The tabline is updated when auto update. I cannot improve it.

So there is no way to avoid the tabline flickering? It is quite annoying

**Comment by Shougo** [comment]
Fixed the error.

> So there is no way to avoid the tabline flickering? It is quite annoying

It is VimL limitation...
`setbufline()` is needed.

**Comment by Shougo** [comment]
Of course, if you can implement it, pull request is well come.

**Comment by petobens** [comment]
Thanks for fixing the error.

> Of course, if you can implement it, pull request is well come.

I wish I could implement but unfortunately I don't have your Vim powers.

**Comment by Shougo** [comment]
I think to re-implement vimshell is better than to fix it.
So it is hard.

**Comment by petobens** [comment]
One very last question: suppose I open a vimshell buffer with `:VimShell` and  then simply press `Q` to quit it. Why do I get a prompt saying:

> Process is running. Force exit? [y/N]

when there is no process running? I expect the vim buffer to quit directly in this case (without the prompt).

**Comment by petobens** [comment]
> I think to re-implement vimshell is better than to fix it. So it is hard.

One related question: I haven't tried Neovim because there is no official windows support yet but I have doubt: Is the new terminal emulator useful? Does it replace vimshell?  If so, how?

**Comment by Shougo** [comment]
> One very last question: suppose I open a vimshell buffer with :VimShell and then simply press Q to quit it. Why do I get a prompt saying:

Thanks.  It is bug.  Fixed.

> One related question: I haven't tried Neovim because there is no official windows support yet but I have doubt: Is the new terminal emulator useful? Does it replace vimshell? If so, how?

I like vimshell than the terminal emulator.

**Comment by petobens** [comment]
Thank you for your awesome support!
