### ISSUE TITLE
Error handling quotes

### ISSUE THREAD

**Issue by petobens** [Shougo/vimshell.vim#213]
If I run `VimShellSendString R -e "print(2)"` the VimShell buffer onlys read `R -e` and not the quotes:

![blahhh](https://cloud.githubusercontent.com/assets/2583971/11957119/54dbfbd2-a89e-11e5-95dc-b638a6ba65d6.gif)

**Comment by Shougo** [comment]
Fixed.

**Comment by petobens** [comment]
Thank you!
