### ISSUE TITLE
How to compiler and run in vimshell quickly?

### ISSUE THREAD

**Issue by ClarkZhang** [Shougo/vimshell.vim#214]
My .vimrc was 
```
map <F5> ggVG=:call CompileRun()<CR>
func! CompileRun()
    exec "w"
    if &filetype == 'c'
        exec "!clang -Wall % -o %<"
        exec "!./%<"
    elseif &filetype == 'cpp'
        exec "!clang++ -Wall -g -std=c++14 % -o %<"
        exec "!./%<"
    elseif &filetype == 'java' 
        exec "!javac %" 
        exec "!java %<"
    elseif &filetype == 'sh'
        exec "!chmod a+x %"
        exec "!./%"
    elseif &filetype == 'python'
        exec "!python %"
    endif
endfunc
```
Now I want to use `:VimShellTab` instead of `:!` so that I can press F5 to run the file in a new split tab. Could you tell me how to change my .vimrc?

**Comment by ujihisa** [comment]
How did you try to change from the code above to achieve that, and what errors did you get from it?

**Comment by ClarkZhang** [comment]
I tried 
```
map <F5> <F3>:call CompileRun()<CR>
func! CompileRun()
    exec "w"
    if &filetype == 'c'
        exec "!clang -Wall % -o %<"
        exec "VimShellExecute %<"
    elseif &filetype == 'cpp'
        exec "!clang++ -Wall -g -std=c++14 % -o %<"
        exec "VimShellExecute %<"
    elseif &filetype == 'java' 
        exec "!javac %" 
        exec "VimShellExecute java %<"
    elseif &filetype == 'sh'
        exec "!chmod a+x %"
        exec "VimShellExecute %"
    elseif &filetype == 'python'
        exec "VimShellExecute python %"
    endif
endfunc
```
If I run a python file. The error is 
```
/usr/bin/python: can't open file '%': [Errno 2] No such file or directory

*Exit*
```
I don't know why % can't denote the file name in `exec "VimShellExecute python %"`.
It works fine with `:VimShellExcute python HelloWorld.py` in normal mode.

**Comment by ujihisa** [comment]
@shougo do you think if we should change `:VimShellExecute` and `:VimShellInteractive` to `expand()` against their `{command}`?

@ClarkZhang for the current version of VimShell, you can run `expand()` beforehand to manual expand `'%'`, or any other ones such as `'#'`.

        execute "VimShellExecute" "python" expand("%")

**Comment by ClarkZhang** [comment]
Thanks,  it works.

**Comment by crazymaster** [comment]
BTW, how about using [vim-quickrun](https://github.com/thinca/vim-quickrun)?

**Comment by ClarkZhang** [comment]
@crazymaster vim-quickrun open an output window not a shell window. Input function doesn't work in output window.

**Comment by Shougo** [comment]
@ClarkZhang `expand("%<")` is invalid expand character.
You should use this `fnamemodify(expand('%'), ':r')`

@ujihisa I don't think vimshell should expand `%`.
Because, it cannot expand `%<`.

**Comment by ujihisa** [comment]
:+1:
