### ISSUE TITLE
MacVim hangs with any interactive commands

### ISSUE THREAD

**Issue by ujihisa** [Shougo/vimshell.vim#216]
e1e6186496b9d2ba32d112b5c170a5be9132d2c0 の変更から、VimShellで何かインタラクティブなコマンド(irbとかsbtとかbashとか)を実行すると、Vimが固まります。

* Gif (固まってるうちにタイムアウトになってしまって固まりカーソルである虹色のぐるぐるが見えないけどほんとうはこのあとでてきます) https://gyazo.com/684ab8d2da9e2cdd8276c52c3457e227
    * 画面からはわからないけれど、`irb`起動後めっちゃ文字入力してます。
* 固まりから復帰後はレイアウトが崩壊 (`<C-l>`で修正可能) https://gyazo.com/74b2f729f2d744325e276457d8905c16
* Insert modeのときのみ発動。Normal modeのままpasteして`<Cr>`などならさくさくと利用可能です。
* `iexe`つけてもつけなくても再現します。

![](https://camo.githubusercontent.com/c0902a34963fbb9067608c148774365033479dd7/687474703a2f2f63646e2d616b2e662e73742d686174656e612e636f6d2f696d616765732f666f746f6c6966652f752f756a69686973612f32303130313031322f32303130313031323133303233342e706e67)

動作環境に用いた環境
* MacVim Kaoriya 7.4.1147
* vimproc master aa075b9b56839e1adb08421d2e9837f90e59acad

**Comment by ujihisa** [comment]
うおおお、バッチリです!

**Comment by Shougo** [comment]
Fixed again.

**Comment by ujihisa** [comment]
いまの最新版でもバッチリing
