### ISSUE TITLE
<Plug>(vimshell_switch) not working

### ISSUE THREAD

**Issue by still-dreaming-1** [Shougo/vimshell.vim#217]
I added this line to my .vimrc:

`nnoremap <leader>v <Plug>(vimshell_switch)`

It doesn't work for me. I have tried it in Vim and in Neovim. Interestingly the following does work:

`nnoremap <leader>v :VimShell<enter>`

**Comment by Shougo** [comment]
```vim
nmap <leader>v <Plug>(vimshell_switch)
```

`:help <Plug>`
