### ISSUE TITLE
Error when execting shell command

### ISSUE THREAD

**Issue by philolo1** [Shougo/vimshell.vim#220]
Hi i installed vimshell on my mac with neovim 0.1.4. I also installed vim-proc. The shell opens without a problem and things like `echo` work. But if i put in the command `ls` i get the following error:

!!!Vim(let):E117: Unknown function: timer_start function vimshell#execute_current_line[1]..vimshell#mappings#execute_line[34]..<SNR>86_execute_command_line[55]..vimshell#parser#eval_script[20]..vimshell#interactive#execute_process_out[5]..<SNR>90_timer_start, line 2!!!
!!!Vim(let):E117: Unknown function: timer_start function <SNR>90_check_all_output[19]..<SNR>90_check_output[48]..vimshell#parser#execute_continuation[2]..vimshell#interactive#execute_process_out[5]..<SNR>90_timer_start, line 2!!!
v

**Comment by Shougo** [comment]
Fixed.

**Comment by philolo1** [comment]
@Shougo thanks, it works 👍
