### ISSUE TITLE
キーボード入力を妨害される

### ISSUE THREAD

**Issue by anekos** [Shougo/vimshell.vim#222]
```
:VimShellInteractive irb
```

などとすると↓のコードが恐らくどのバッファでも定期的に実行されるようで、キーの入力が妨害されてしまいます。
超スピードで入力しないと検索もできません。
超スピードで入力できるようになるオプションがほしいです。

gVim 7.4.1910-1 on Arch Linux
https://github.com/Shougo/vimshell.vim/blob/5a8d260041adc447ce6045ad516e790d2a748c15/autoload/vimshell/interactive.vim#L815

**Comment by Shougo** [comment]
g:vimshell_interactive_update_time の値を変更するか、Vim を更新してください。
Vim を新しくするとタイマーを利用するようになります。

**Comment by anekos** [comment]
失礼しました。
うまくいったようです。
ありがとうございます!
