### ISSUE TITLE
Deleting past prompt string

### ISSUE THREAD

**Issue by still-dreaming-1** [Shougo/vimshell.vim#223]
I was having issues with my normal mappings not working right, so I set `g:vimshell_no_default_keymappings = 1` This did fix that issue, but now it is really easy to delete past the the prompt string. Once that happens, it stops accepting commands. Is there a trick to fixing this?

**Comment by still-dreaming-1** [comment]
Actually not accepting commands has nothing to do with deleting past the prompt string. This is just what happens when you turn that setting on.

**Comment by still-dreaming-1** [comment]
Ok, I think I'm staring to figure this out. Editing the test in insert mode does not on it's own affect what is sent to this shell. It was the predefined mappings that did this. Is that right? Looking through the documentation there are a ton of mappings that can be set, but it does not say what the defaults are.

**Comment by Shougo** [comment]
You have disabled the mapping.
It is feature.
