### ISSUE TITLE
Outputs wait for users' `i_<CR>`

### ISSUE THREAD

**Issue by ujihisa** [Shougo/vimshell.vim#224]
Since c71ffb48b9ea2c718facd2eaad431f59503e58aa, external command outputs will not show up unless you press at least one `i_<CR>` if you start the process with `n_<CR>`

A way to reproduce: `<Esc>:VimShell<Cr>iruby -e 'p 1'<Esc><Cr>`

* expected: the output `1` shows up immediately
* actual: it shows up only after `i<Cr>`

Environment

* 7.4.1342
* `has('timers') == 0`

**Comment by Shougo** [comment]
Fixed.

**Comment by ujihisa** [comment]
Hmm, still that bug is reproducible in the same way

**Comment by Shougo** [comment]
I cannot reproduce it.
It is the latest version?

**Comment by ujihisa** [comment]
My bad... now it worked.
