### ISSUE TITLE
Use Windows gvim with shell=zsh from cygwin?

### ISSUE THREAD

**Issue by reckoner** [Shougo/vimshell.vim#225]
Is is possible to use vimshell in windows where the underlying shell sits on a cygwin shell (like `zsh`) instead of windows `cmd`? In other words, running gvim.exe (not using cygwin's vim), is it possible to have an embedded `bash` or `zsh` inside of `vimshell`?

I hope that made sense.

**Comment by Shougo** [comment]
No.  vimshell is not terminal emulator.
