### ISSUE TITLE
Scroll output and overwrite previous run

### ISSUE THREAD

**Issue by blayz3r** [Shougo/vimshell.vim#230]
Is it possible to scroll up the output buffer to see more of your output 
![scroll](https://cloud.githubusercontent.com/assets/12205650/25065500/3cae1fc0-21df-11e7-9b65-4fbf281b80f6.png)

Is it possible to set up execution so as to overwrite the split created when running the same file.
![overwrite](https://cloud.githubusercontent.com/assets/12205650/25065550/e85ab126-21df-11e7-9534-37c922f74cd5.png)

.

**Comment by Shougo** [comment]
> Is it possible to scroll up the output buffer to see more of your output

`:help g:vimshell_scrollback_limit`

> Is it possible to set up execution so as to overwrite the split created when running the same file.

Not possible.

**Comment by blayz3r** [comment]
Thanks!
