### ISSUE TITLE
Cannot kill the application by Ctrl - C on Win10

### ISSUE THREAD

**Issue by searene** [Shougo/vimshell.vim#231]
I cannot kill the application by Ctrl - C on Win10, there is no response.

Can you help make it work? Thanks.

**Comment by Shougo** [comment]
We have not ESP skills.
Please provide the more information(the reproduce ways and the minimal vimrc).

**Comment by searene** [comment]
@Shougo Sorry, this is my .vimrc, I use `Vundle` to install `VimShell`

```
set nocompatible        " be iMproved, required
filetype off                  " required

set rtp+=$HOME/vimfiles/bundle/Vundle.vim/
call vundle#begin('$USERPROFILE/vimfiles/bundle/')
endif

Plugin 'gmarik/Vundle.vim'

Plugin 'Shougo/vimshell.vim'
Plugin 'Shougo/vimproc.vim'

call vundle#end()            " required
filetype plugin indent on    " required
```

Steps to reproduce the problem.

1. Open gvim
2. Run `:VimShell`
3. Run `sleep 10`
4. Press `Ctrl + C`, no response.

**Comment by Shougo** [comment]
Hm.  I think it is does not work in Windows.
Please use `<Plug>(vimshell_hangup)` instead.
