### ISSUE TITLE
VimShell seem slow when compile (Angular CLI)

### ISSUE THREAD

**Issue by banminkyoz** [Shougo/vimshell.vim#233]
![image](https://user-images.githubusercontent.com/29815830/30025275-e95c9b2a-91a1-11e7-963c-2c9963590285.png)

I installed VimShell and everything work fine..
But when i tried to run ng serve (CLI).. It takes really long time to finish..Normally, i'll just take 10-20 seconds.

Am i missing somethings ? Thanks :D

**Comment by Shougo** [comment]
vimshell is not optimized and Vim script is very slow.
I cannot fix it.
