### ISSUE TITLE
vimshell cann't work with racket 

### ISSUE THREAD

**Issue by gou4shi1** [Shougo/vimshell.vim#236]
![2018-01-07 21-08-11](https://user-images.githubusercontent.com/16915589/34649693-018cf2b2-f3ef-11e7-8f3b-9c5bb1a4e9df.png)
when I leave the buffer of vimshell and then enter again, the racket was abort with "SIGSEGV MAPERR si_code 1 fault on addr 0xffffffffffffffff"

**Comment by gou4shi1** [comment]
If I use `VimShellInteractive`
it will work fine sometimes
and work bad ("SIGSEGV MAPERR si_code 1 fault on addr 0xffffffffffffffff") sometimes

**Comment by Shougo** [comment]
I think it is racket bug.
It should be reported in racket.
