### ISSUE TITLE
tree output not displayed properly

### ISSUE THREAD

**Issue by rpuntaie** [Shougo/vimshell.vim#237]
```
vimshell% tree
Folder PATH listing for volume OS
Volume serial number is 00000068 5D13:2150
C:.
ÃÄÄÄcode
ÀÄÄÄdoc
    ÀÄÄÄ_static
```

expected

```
Folder PATH listing for volume OS
Volume serial number is 000000B2 5D13:2150
C:.
├───code
└───doc
    └───_static
```

This was on Windows 10. 

Is it possible to make this work locally or is this a vimshell shortcoming?

I like vimshell.

**Comment by rpuntaie** [comment]
On Linux it is better. I think my Vim font on Windows is the reason. What font do you suggest?

**Comment by Shougo** [comment]
I don't know about the font.
I think the font for programmer available.
