### ISSUE TITLE
How can I resolve key mapping conflict?

### ISSUE THREAD

**Issue by modood** [Shougo/vimshell.vim#238]
How can I resolve key mapping conflict?

For example(normal mode):

My:
```html
<C-l>     moves one viewport to the right
```

vimshell:
```html
<C-l>     <Plug>(vimshell_clear)
```

I don't want to use `g:vimshell_no_default_keymappings`.
Because it will disables all default key mappings in vimshell but I just want to change one or two.

**Comment by Shougo** [comment]
```vim
autocmd FileType vimshell s:on_vimshell()

function! s:on_vimshell()
  unmap <buffer> <C-l>
endfunction
```

**Comment by modood** [comment]
@Shougo Thanks, It work :+1: 

But `s:on_vimshell` should be called:
```viml
autocmd FileType vimshell call s:on_vimshell()
```
